### PR TITLE
Final Touches - Only thing left is Signup, a few pages, and the secret page

### PR DESCRIPTION
**Pull request by whippingdot**
This PR is for the final touches before the first post. This will hide uncompleted profiles, add a dark mode toggle, add a light mode, and maybe make a dark/light for my portfolio and change some stuff for my portfolio. Switch the repl (if not done) to this branch for the finishing touches before posting.

### CODE REVIEW

**Comment by whippingdot** [comment]
Credit to Dark/Light toggle: https://dev.to/ananyaneogi/create-a-dark-light-mode-switch-with-css-variables-34l8 by @ananyaneogi (sry for ping if you got it)

**Comment by whippingdot** [comment]
@headiscoding @Isaiah08-D @JBYT27 @Codemonkey51 Finish ur pages if not done

**Comment by zghwi** [comment]
Oh I didn't finish my portifolio

**Review by zghwi — APPROVED** [review]
Awesome
I know my portfolio is not done, but, ngl, its a fibonacci calculator

**Comment by whippingdot** [comment]
lul bruh add some HTML puhlease @zplusfour

**Review by darkdarcool — APPROVED** [review]
Looks good to me! I like that we have a dark mode even though we really don't need it. I think that this was a really good idea!

**Comment by whippingdot** [comment]
@darkdarcool credit to @JBYT27 for the suggestions and @ananyaneogi for the dev post 😁 . Ima add my page's dark toggle and I think i will merge. Please tell me if I should wait so you can finish ur pages

**Review by darkdarcool — APPROVED** [review]

**Comment by kokonut27** [comment]
I finished my portfolio. Not much, but yea

**Comment by PotentialStyx** [comment]
I'll review my page one more time rn

**Review by BD103 — APPROVED** [review]
Noice

```python
class Review:
  def __init__(self):
    self.accepted = False
    self.comment = "No Comment"
  def approve(self, comment=None):
    self.accepted = True
    if comment is not None:
      self.comment = comment

my_review = Review()
my_review.approve(comment="Good job!")
```

**Comment by whippingdot** [comment]
Which file is that @BD103  
@JBYT27 Push changes?...
@Codemonkey51 vat?

Oh and also I have to copy paste the html done in the Index.html file into the signup page. We also might need to change the css for the button in the sign up page with the change of light mode...Give ur opinion on that

**Comment by whippingdot** [comment]
bRuH wHaT wHo added THE AWESOME SMOOTH TRANSITION FOR THE ENLARGMENT OF THE ABOUT PAGE SIGN. Also I thought we didn't need text so I removed it...Do we need the text?

**Comment by whippingdot** [comment]
bRuH @darkdarcool and @BD103 I ain't gonna complain but the whole website is busted. The light mode reset all the website's custom css's. Me and @ColePete are fixing it right now. Why in the world wud u approve the changes...

**Comment by whippingdot** [comment]
@CodingRedpanda ur page isn't broken but ur css was always the same as the main page so now it is on light mode. If u want I can add a toggle to ur page too...

EDIT: Ima add the toggle, tell me if u don't want it
EDIT: @ColePete's the man, he told me not to add the switch and just to add the old css properties. Doing it now

**Comment by ghost** [comment]
@whippingdot thats a lot of changes!

**Comment by whippingdot** [comment]
OOps I meant @EpicRaisinGaming not @epicraisin

**Comment by whippingdot** [comment]
@ColePete BTW this is the commit message if u didn't see it
> Me and @ColePete fixed people's profiles that were going wrong. We mainly fixed his. After that I fixed @CodingRedpanda's (check it it is still kinda broken), and I fixed a problem where in @epicraisin's the link is unreasonably long (i did that sry). I also fixed main page CSS coming onto ur pages and I fixed that messing up the heading and toggle switch. I changed my page, fixing the advertisement I already had, and added three more advertisements. I also added my page on the bottom of the main page (i did create the org) and finally fixed @darkdarcool's background becoming pale

EpicRaisin supposed to be @EpicRaisinGaming

**Comment by ghost** [comment]
I saw thx tho

**Comment by ghost** [comment]
hey, also, do I have like a specific job in this org, or do I just do whatever is needed?

**Comment by whippingdot** [comment]
Do whatever is needed 🤣

**Review by PotentialStyx — APPROVED** [review]
Looks Good!

**Comment by whippingdot** [comment]
Thanks. Ima not merge for a day or two to see if anyone makes the signup work but if not then...

**Comment by whippingdot** [comment]
@zplusfour NOOOOO WHY DID YOU CHANGE UR PFP NOOOOOOOOOOOOOOOOOOOOO

**Comment by whippingdot** [comment]
@AmazingMech2418 @cursorweb @Codemonkey51 @EpicRaisinGaming @elipie not to be mean to the rest of us but i think they are the most advanced in coding in this org. @programmeruser2 might also be very advanced but I have NO idea lul. If you guys could use some of ur time to make the sign up page work I would be happy. We need it to be sent to a file/db so PUHLEASE DO IT! If u guys can't then one of us or a few of us together please do eeeet

**Comment by whippingdot** [comment]
bRuHtEr me god lul. Bruh I did sooo many things. Now all we have to do in the secret page is make it so the pictures are bigger. I have done many things already and I won't be able to resize the images but if someone can please resize the images (trying to keep them all the same size) but make sure they still have the same dimensions. Also make sure the images are readable. We can't have the billy one too small or you won't be able to read the text...

**Comment by firefish111** [comment]
> bRuH wHaT wHo added THE AWESOME SMOOTH TRANSITION FOR THE ENLARGMENT OF THE ABOUT PAGE SIGN. Also I thought we didn't need text so I removed it...Do we need the text?

i did

**Comment by firefish111** [comment]
haha secret page go bye bye

**Comment by whippingdot** [comment]
@firefish111 what is wrong with you I worked so hard on that. Ima bring it back. Don't delete the secret page, why did you do that!

**Review by darkdarcool — APPROVED** [review]
LGTM!

**Comment by whippingdot** [comment]
@darkdarcool u said u wud add better styles to the secret page. Do that. Someone else PLEASE MAKE THE SIGNUP PAGE WORK

**Comment by darkdarcool** [comment]
lol i said I would add text, and now I'm too lazy so i'll jsut leave it alone. AND. I made a different repl that had from data go to a txt file.

**Comment by ghost** [comment]
@whippingdot may i ask, how to access the secret page, and why we have it?

**Comment by whippingdot** [comment]
/secret and for no reason. I won't tell you the other way @JBYT27 and @darkdarcool know on how to access the secret page

**Comment by ghost** [comment]
> /secret and for no reason. I won't tell you the other way @JBYT27 and @darkdarcool know on how to access the secret page

hmmm..... _suspicious_......

**Comment by ghost** [comment]
Also, NO ONE IS ALLOWED TO LOOK AT MY PAGE YET! I AM STILL WORKING ON A SUPRISE! plz don't ruin it.

**Comment by darkdarcool** [comment]
lol

**Review by darkdarcool — COMMENTED** [review]
lol plz take out fortnite stuff.(i hate that game)

**Comment by firefish111** [comment]
haha é

**Comment by ghost** [comment]
@whippingdot I am pretty sure that if you look up online how to make a signup page, you will figure out how to make ours work. If you want.

**Comment by whippingdot** [comment]
Hey guys, I followed what @ColePete said and found a website. All I need now is someone to create an email for our organization. I can't cause my dad might get angry, so can anyone please create an email for our org (gmail / outlook / hotmail) with the email address being something like ReplCoders@blah.com. Password can be ReplItCoders (i will delete this message after the mail is made). If someone finds the password i will tell u all the new password. Also do not use this email for ANYTHING ELSE as it is not funny (👀 @firefish111 @headiscoding)!

**Review by darkdarcool — APPROVED** [review]
LGTM!

**Comment by whippingdot** [comment]
@darkdarcool did you create an email? I need an email for our organization.

**Comment by darkdarcool** [comment]
no i didn't. my parents would be mad

**Comment by whippingdot** [comment]
lul same as me...anyone else?

> Also I asked cause you said LGTM

**Comment by ghost** [comment]
I can when I get home today, I will tell yall the information once i create it. I am glad that my idea helped. @whippingdot

**Comment by ghost** [comment]
@whippingdot 
image
the email is ready!

**Comment by whippingdot** [comment]
Hey guys the /signup page downloads something. Can you help with the routing?

**Comment by whippingdot** [comment]
Yoit me @Codemonkey51 workin on it

**Comment by PotentialStyx** [comment]
I think we killed the repl lmao

**Comment by whippingdot** [comment]
we did

**Comment by PotentialStyx** [comment]
> we did

Now we need to wait 30 min without going to the server for it to restart (wait no it's always on), or ask a replit team to fix. Idek what we did.

**Comment by ghost** [comment]
oops

Hey, @whippingdot, can you push a new version, I was still foxing some things up. SRY

**Comment by ghost** [comment]
*Fixing

**Comment by PotentialStyx** [comment]
Wait... always on hmmm so in a few hours it should fix itself lmfao

**Comment by whippingdot** [comment]
lul

can't i just create a new repl 😁

**Comment by PotentialStyx** [comment]
> lul
> 
> can't i just create a new repl 😁

I mean you can... ~~but what's the fun in that~~

**Comment by ghost** [comment]
Whip, did you see my comment?

EDIT: The repl works for me. IDK y you cant

**Comment by whippingdot** [comment]
Lul it doesn't work for me or @Codemonkey51

**Comment by ghost** [comment]
hmmmm... wonder why...

**Comment by whippingdot** [comment]
Guys, I created a new repl, gonna invite all of you
> I mean you can... ~~but what's the fun in that~~

lul sorry done

**Comment by ghost** [comment]
ok then you need a new github page BTW

**Comment by PotentialStyx** [comment]
> hmmmm... wonder why...

Idk, seems like it did a bad. I even restarted by device lmfao

**Comment by whippingdot** [comment]
No @ColePete I linked to this itslef

**Comment by whippingdot** [comment]
Why wud you need a new github page 🤦

**Comment by ghost** [comment]
oh, then never mind i didn't know that you could use the same github twice

**Comment by whippingdot** [comment]
Lul @Codemonkey51 really sorry for doing that. Sorry Sorry Sorry!!! Please don't be angry at me

**Comment by ghost** [comment]
> Lul @Codemonkey51 really sorry for doing that. Sorry Sorry Sorry!!! Please don't be angry at me

Yeah, me too. I am sry

**Comment by PotentialStyx** [comment]
It was funny :D, just a bit annoying, but luckily we finished (most) the code already

**Comment by ghost** [comment]
lol

**Comment by whippingdot** [comment]
Wait q are we actually done? I kinda rushed on merging. We finished the signup, the secret page, and that is all right. Darkdarcool said he would change teh secret page so he can do that after the post is shared as well right @darkdarcool

**Comment by ghost** [comment]
@whippingdot **WE** are done, yes. **BUT** I would wait a little to post it in case someone has more work that they want to do and just isn't seeing these right now

**Comment by whippingdot** [comment]
koi koi! Can I post the 26th morning for u guys? That is giving you 8 hrs till the post

**Comment by ghost** [comment]
@whippingdot I don't really care when you post I was just saying to give everyone some time before you post. *(Like you have already)*

**Pull request merged**
